# https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake

name: CMake Build Matrix

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu Latest GCC",
              artifact: "Linux",
              os: ubuntu-20.04,
              build_type: "Release", cc: "gcc"
            }
    steps:
    - uses: actions/checkout@v1

    - name: Download and build dependencies
      run: bash .github/liboqs.sh

    - name: Configure
      shell: bash
      run: |
        CC=${{ matrix.config.cc }}

        cmake \
            -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}

    - name: Build
      shell: bash
      run: cmake --build build

    - name: Run tests
      shell: bash
      run: cd build && ctest

    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.artifact }}
        path: |
          ./build/bin/*
          ./build/lib/*
        retention-days: 7
        if-no-files-found: error


  tests:
    if: contains(github.ref, 'tags/v')
    runs-on: self-hosted
    needs: build
    timeout-minutes: 0
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Download dependencies
      run: sudo apt-get install python3 virtualenv

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2

    - name: Run tests
      run: |
        mkdir -p build build/results build/bin
        ls -lah .
        mv ./Linux/bin/* build/bin
        chmod +x ./build/bin/*
        bash graphics/run_tests.sh

    - name: Generate CSVs
      run: |
        sudo apt install -y nodejs npm
        npm i parse-markdown-table-cli
        ls -lah .
        ls -lah ./build
        bash graphics/convert_tables.sh

    - name: Run tests for FO_AKE
      run: |
        bash graphics/build-fo-ake.sh

    - name: Download dependencies
      run: sudo apt install python3 virtualenv

    - name: Compute graphics
      run: |
        virtualenv --python=python3 venv
        source venv/bin/activate
        pip install -r graphics/requirements.txt
        python graphics/generate_graphics.py graphics/config.yaml
        python graphics/generate_graphics_time.py graphics/config.yaml
        python graphics/generate_graphics_foake_vs_fsxy.py graphics/config.yaml
        bash graphics/cut-images.sh

    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: ./build/results
        retention-days: 7

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-20.04
    needs: tests

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

    - uses: actions/upload-artifact@v1
      with:
        path: ./upload_url
        name: upload_url

  publish:
    if: contains(github.ref, 'tags/v')
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux",
            os: ubuntu-20.04
          }
        # - {
        #     name: "macOS Latest Clang", artifact: "macOS.tar.xz",
        #     os: ubuntu-20.04
        #   }
    needs: release

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./

    - name: Download results
      uses: actions/download-artifact@v1
      with:
        name: results
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url

    - name: Compress results
      run: |
        zip -r results.zip *.csv *.txt *.png
        zip -r Linux.zip bin/*

    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./Linux.zip
        asset_name: Linux.zip
        asset_content_type: application/zip

    - name: Upload to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./results.zip
        asset_name: ./results.zip
        asset_content_type: application/zip
